package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

filegroup(
    name = "dictionary",
    srcs = glob([
        "*.pb",
        "*.bin",
        "*.txt",
    ]),
)
