sh_binary(
    name = "build_pip_pkg",
    srcs = ["build_pip_pkg.sh"],
    data = [
        "LICENSE",
        "MANIFEST.in",
        "README.md",
        "setup.py",
        "//dictionary",
        "//nori/python/nori:nori_py",
    ],
)
