load("@rules_cc//cc:defs.bzl", "cc_library")

package(
    default_visibility = [
        "//nori:__pkg__",
        "//nori:__subpackages__",
    ],
    licenses = ["notice"],
)

cc_library(
    name = "constant",
    srcs = [],
    hdrs = ["constant.h"],
    deps = [
        "@com_google_absl//absl/strings",
    ],
)
