package(
    default_visibility = [
        "//nori:__pkg__",
        "//nori:__subpackages__",
    ],
    licenses = ["notice"],
)

filegroup(
    name = "dictionary",
    srcs = glob([
        "*.pb",
        "*.bin",
        "*.txt",
    ]),
)
