name: Build and test all

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        # python-version: ["3.7", "3.8", "3.9", "3.10"]
        include:
          - os: macos-latest
            bazel-target: darwin
          - os: ubuntu-latest
            bazel-target: linux

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

    - name: Check code style
      run: cargo fmt --all -- --check

    - name: Test
      run: cargo test

    - name: Build
      run: cargo build --release --all-features
