package(
    default_visibility = [
        "//nori:__pkg__",
        "//nori:__subpackages__",
    ],
    licenses = ["notice"],
)

filegroup(
    name = "listDirectory",
    srcs = glob(["listDirectory/*"]),
)

filegroup(
    name = "tokenInfoDictionary",
    srcs = glob(["tokenInfoDictionary/*"]),
)
